---
- hosts: localhost
  connection: local

  tasks:

  - name: Essential dev tools
    dnf: name={{ item }} state=installed
    become: true
    with_items:
      - vim
      - tmux
      - git
      - git-extras
      - zsh
      - zeal
      - the_silver_searcher
      - fzf
      - libvirt
      - qemu
      - cloc
      - jq
      - virt-manager
      - java-1.8.0-openjdk-devel
      - docker
      - chromium
      - snapd

  - name: Docker service
    service:
      name: docker 
      state: started
      enabled: yes

  - name: Docker group
    group:
      name: docker
      state: present
    become: true

  - name: Add user to Docker group
    user:
      name: "{{ user }}"
      groups:
        - wheel
        - docker
    become: true

  - name: Vagrant
    dnf: name=https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.rpm state=present
    become: true

  - name: Virtualbox
    dnf: name=http://download.virtualbox.org/virtualbox/5.2.4/VirtualBox-5.2-5.2.4_119785_fedora26-1.x86_64.rpm state=present
    become: true

  - name: Packer
    unarchive:
      src: https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
      dest: /opt
      creates: /opt/packer
      remote_src: True
    become: true

  - name: vscode
    dnf: name=https://packages.microsoft.com/yumrepos/vscode/code-1.19.1-1513676713.el7.x86_64.rpm state=present
    become: true

  - name: Utils
    dnf: name={{ item }} state=installed
    become: true
    with_items:
      - tree
      - moreutils
      - pv
      - dtrx
      - xsel

  - name: Debugging/Tracing tools
    dnf: name={{ item }} state=installed
    become: true
    with_items:
      - htop
      - tcpdump
      - iotop
      - nethogs
      - nload
      - ifstat
      - iperf
      - strace
      - ngrep
      - mtr
      - siege
      - iptraf
      - nmon
      - sysstat

  - name: InfoSec
    dnf: name={{ item }} state=installed
    become: true
    with_items:
      - nmap

  - name: Python tools requirements
    dnf: name={{ item }} state=installed
    become: true
    with_items:
      - gcc
      - redhat-rpm-config
      - libffi-devel
      - openssl-devel
      - python-devel
      - libxml2-devel
      - libxml-devel
      - libxslt-devel
      - libselinux-python
      - python3-pip
      - python3-devel

  - name: Tmux plugin manager (tpm)
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: "{{ home }}/.tmux/plugins/tpm"

  - name: Tmux config
    copy:
      src: "{{ home }}/environment/tmux.conf"
      dest: "{{ home }}/.tmux.conf"

  - name: Pathogen dir
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ home }}/.vim/autoload"
      - "{{ home }}/.vim/bundle"

  - name: Install Pathogen
    get_url:
      url: https://tpo.pe/pathogen.vim
      dest: "{{ home}}/.vim/autoload/pathogen.vim"

  - name: vim config
    copy:
      src: "{{ home }}/environment/vimrc"
      dest: "{{ home }}/.vimrc"

  - name: Vim plugins
    git:
      repo: "{{ item }}"
      dest: "{{ home }}/.vim/bundle/{{ item | basename }}"
    with_items:
      - https://github.com/vim-airline/vim-airline
      - https://github.com/scrooloose/nerdtree
      - https://github.com/flazz/vim-colorschemes
      - https://github.com/ctrlpvim/ctrlp.vim
      - https://github.com/tpope/vim-fugitive
      - https://github.com/rodjek/vim-puppet
      - https://github.com/vim-ruby/vim-ruby
      - https://github.com/tpope/vim-obsession
      - https://github.com/vim-syntastic/syntastic
      - https://github.com/pearofducks/ansible-vim
      - https://github.com/fatih/vim-go
      - https://github.com/KabbAmine/zeavim.vim
      - https://github.com/ekalinin/Dockerfile.vim

  - name: Git config
    template:
      src: "{{ home }}/environment/gitconfig.j2"
      dest: "{{ home }}/.gitconfig"

  - name: Python tools
    pip: name={{ item }} state=present
    become: true
    with_items:
      - lxml
      - sshuttle
      - icdiff
      - httpie
      - ansible-lint
      - molecule
      - docker
      - python-vagrant
      - pylint
      - autopep8
      - tox

  - name: mitmproxy
    pip: name=mitmproxy state=present extra_args=--user executable=pip3

  - name: Ansible development
    pip: name={{ item }} state=present extra_args=--user
    with_items:
      - pytest
      - virtualenvwrapper
